services:
  mysql-mailcow:
    ports:
      - "${HTTPS_BIND}:${SQL_PORT:-127.0.0.1:13306}:3306"

  redis-mailcow:
    ports:
      - "${HTTPS_BIND}:${REDIS_PORT:-127.0.0.1:7654}:6379"
  dovecot-mailcow:
    ports:
      - "${HTTPS_BIND}:${DOVEADM_PORT:-127.0.0.1:19991}:12345"
      - "${HTTPS_BIND}:${IMAP_PORT:-143}:143"
      - "${HTTPS_BIND}:${IMAPS_PORT:-993}:993"
      - "${HTTPS_BIND}:${POP_PORT:-110}:110"
      - "${HTTPS_BIND}:${POPS_PORT:-995}:995"
      - "${HTTPS_BIND}:${SIEVE_PORT:-4190}:4190"

  postfix-mailcow:
    ports:
      - "${HTTPS_BIND}:${SMTP_PORT:-25}:25"
      - "${HTTPS_BIND}:${SMTPS_PORT:-465}:465"
      - "${HTTPS_BIND}:${SUBMISSION_PORT:-587}:587"

  nginx-mailcow:
    ports:
      - "${HTTPS_BIND:-}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "${HTTP_BIND:-}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
